# Generated by Django 5.1 on 2024-09-02 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
